language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

sudo: false

before_install:
    # Prevent "Please tell me who you are" errors for certain DZIL configs
    - git config --global user.name "TravisCI"
    - |
      if perl -e 'if ($] < "5.008009") { exit(0) } else { exit(1) }'; then
        perlbrew --notest install -v perl-5.8.9
        perlbrew use perl-5.8.9
        perl --version
      fi

install:
    # Deal with all of the DZIL dependancies, quickly and quietly
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla~'>=5.04'
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
    # This is the list from 'dzil listdeps', hardcoded here because Dist::Zilla::Plugin::Git
    # won't install on perl-5.8.
    - cpanm --verbose --skip-satisfied --notest B Carp Devel::Callsite Digest::MD5 Exporter ExtUtils::MakeMaker Fcntl File::Basename IO::File IO::Pipe PadWalker POSIX Scalar::Util Socket Sub::Name Test::Builder Test::More

script:
    - prove -l

